pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CI
  displayName: "Run lint, build"
  steps:
  - task: PowerShell@2
    displayName: 'Set GitHub Token'
    inputs:
      targetType: 'inline'
      script: |
        Set-Content -Path .npmrc -Value "${{ parameters.serviceconnection }}" 
                Add-Content -Path .npmrc -Value "//npm.pkg.github.com/:_authToken=$(GitHubPAT)"
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'ci'
    displayName: 'Install Dependencies'
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run lint'
    displayName: 'Lint'
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build --if-present'
    displayName: 'Build TypeScript'
